spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        format_sql: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 90000000           # 15 minutes
    refresh-expiration-ms: 60480000000 # 7 days
  client-url: http://localhost:5000

logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.orm.connections.pooling: ERROR
    
server:
  servlet:
    context-path: /api