spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_meet
    username: admin
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.orm.connections.pooling: ERROR